apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bian-architecture
  description: BIAN Architecture documentation and API compliance guidelines
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: documentation
  lifecycle: production
  owner: group:default/users
